# For more info on Python, GitHub Actions, and Azure App Service 
# please head to https://aka.ms/python-webapps-actions

name: Build and deploy Notejam app to Azure App Service

on:
  push:
    branches: 
      - main

env:
  WEBAPP_NAME: 'notejamapp'
  ARM_CLIENT_ID: ${{secrets.TF_ARM_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.TF_ARM_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.TF_ARM_TENANT_ID}}
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python version
      uses: actions/setup-python@v2
      with:
        python-version: 2.7

    - name: Create and start virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: python manage.py test
    
    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v2
      with:
        name: python-app
        path: |
          . 
          !venv/

  cloud-infra-setup:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan
      - name: terraform Apply
        run: terraform apply -auto-approve

  deploy-to-webapp:
    needs: cloud-infra-setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
      
      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}
    
      - name: Disable static collection and set migration command on App Service
        uses: Azure/appservice-settings@v1
        with:  
          app-name: ${{ env.WEBAPP_NAME }}
          app-settings-json: '[{ "name": "DISABLE_COLLECTSTATIC", "value": "true" }, { "name": "POST_BUILD_COMMAND",  "value": "python manage.py syncdb && python manage.py migrate && python manage.py runserver" }, { "name": "SCM_DO_BUILD_DURING_DEPLOYMENT", "value": "true" }, { "name": "DJANGO_ENV", "value": "production"}]'
      
      - name: Build using AppService-Build
        uses: azure/appservice-build@v2
        with:
          platform: python
          platform-version: '2.7'

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME}}
          slot-name: 'production'

